# Site settings
title: Surveying with Qualtrics (Introduction)
email: training@intersect.org.au
description: "Surveying with Qualtrics: An introductory course for Researchers"
remote_theme: "IntersectAustralia/intersect-training-theme"

#baseurl: "/getting-started-with-HPC"
#url: "http://www.intersect.org.au"

# Build settings
markdown: kramdown
permalink: pretty
